version: "3.7"

services:
  api:
    ports:
      - "5000:5000"
    image: gluck0101/oridosai-img2txt:latest
    build:
      dockerfile: ./api/Dockerfile
      context: .
    volumes:
      - ./api:/home/user/api
